Join HomWork
mate-academy/jv-join pull request #232
Opened 2022-05-06 11:17 UTC by yuriikozar

Solution + Checkstyle
v1

2022-05-09 10:45 UTC, dSkarzh approved these changes

2022-05-13 15:51 UTC, KseniiaMakarova requested changes

2022-05-13 15:51 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/Main.java
> +        cars.forEach(System.out::println);
давай и остальные методы carService протестируем

2022-05-13 15:51 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +            return numberOfDeletedRows != 0;
```suggestion
            return numberOfDeletedRows > 0;
```

2022-05-13 15:51 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +                + "JOIN cars_drivers cd ON d.id = cd.driver_id WHERE cd.car_id = ?;";
и где драйвер не удален

2022-05-13 15:51 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +            throw new DataProcessingException("Can't get drivers from car with id: " + carId, e);
```suggestion
            throw new DataProcessingException("Can't get drivers for car with id: " + carId, e);
```

2022-05-13 15:51 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +    private void insertDrivers(Car car) {
у тебя уже есть метод createCarsDriversRelation

2022-05-13 15:51 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/model/Car.java
> +    public Car(Long id, String model, Manufacturer manufacturer, List<Driver> drivers) {
нам нужны все 3 конструктора?

2022-05-13 15:51 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/util/ConnectionUtil.java
> +    private static final String URL = "jdbc:mysql://localhost:3306/taxi_service_db";
в init_db.sql схема называется иначе

2022-05-16 06:37 UTC, Sofasmile requested changes
🔥

2022-05-16 06:37 UTC, Sofasmile commented on src/main/java/mate/jdbc/Main.java
> +        audiDrivers.add(driverBob);// List.of(driverBob, driverAlice);
do we need this comment?

2022-05-16 06:37 UTC, Sofasmile commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +
remove empty line

2022-05-16 06:37 UTC, Sofasmile commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +                + "AND is_deleted = FALSE;";
```suggestion
                + "where id = ? AND is_deleted = FALSE;";
```

2022-05-16 06:37 UTC, Sofasmile commented on src/main/java/mate/jdbc/service/CarServiceImpl.java
> +                + "by id = " + id));
```suggestion
                + "Could not get car from DAO by id = " + id));
```

2022-05-16 08:35 UTC, Sofasmile approved these changes

2024-02-15 18:24 UTC, closed without merging