jv-join
mate-academy/jv-join pull request #315
Opened 2022-07-23 08:06 UTC by morozovyrv

2022-07-25 10:29 UTC, MaliukDaria requested changes

2022-07-25 10:29 UTC, MaliukDaria commented on src/main/java/mate/jdbc/Main.java
> +        driver4 = driverService.create(driver4);
It's bad practice to use numbers in variable names

2022-07-25 10:29 UTC, MaliukDaria commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +                + "where cars_drivers.car_id = ?";
```suggestion
        String query = "SELECT * from drivers "
                + "JOIN cars_drivers "
                + "ON drivers.id = cars_drivers.driver_id "
                + "WHERE cars_drivers.car_id = ?";
```

2022-07-25 10:29 UTC, MaliukDaria commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +            throw new DataProcessingException("Couldn't delete car by id " + id + ".", e);
not informative exception message

2022-07-25 10:29 UTC, MaliukDaria commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +        String query = "DELETE FROM `cars_drivers` WHERE car_id = ?";
```suggestion
        String query = "DELETE FROM cars_drivers WHERE car_id = ?";
```

2022-08-01 05:48 UTC, Nick97-git requested changes

2022-08-01 05:48 UTC, Nick97-git commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +            throw new DataProcessingException("Couldn't get list of cars.", e);
```suggestion
            throw new DataProcessingException("Couldn't get list of cars for driver: " + driver, e);
```

2022-08-01 09:23 UTC, Nick97-git approved these changes

2023-02-02 13:48 UTC, closed without merging