Hw 23 jv join
mate-academy/jv-join pull request #451
Opened 2022-12-07 19:00 UTC by SichniyAndriy

2022-12-08 11:46 UTC, Rommelua requested changes

2022-12-08 11:46 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +                + "INNER JOIN drivers D ON CD.driver_id = D.id "
```suggestion
                + "INNER JOIN manufacturers m ON C.manufacturer_id = M.id "
                + "INNER JOIN cars_drivers cd ON C.id = CD.car_id "
                + "INNER JOIN drivers d ON CD.driver_id = D.id "
```
always use lowercase for sql aliases

2022-12-08 11:46 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +    public Car update(Car car) {
You are updating drivers here, but what about manufacturer, model ?

2022-12-08 11:46 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +        String query = "UPDATE cars SET is_deleted = TRUE WHERE id = ?";
you have 'TRUE' here, but 'false' in getAll
use one style (upper or lower)

2022-12-08 11:46 UTC, Rommelua commented on src/main/java/mate/jdbc/service/CarServiceImpl.java
> +    }
```suggestion
```
Do not create extra methods

2022-12-08 11:46 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +    public void fillCarsDriversTable() {
Do not create extra methods

2022-12-09 11:31 UTC, Rommelua requested changes
almost good

2022-12-09 11:31 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +                "UPDATE manufacturers SET name = ?, country = ? WHERE id = ?";
You should update cars, not manufacturers 
```
        String query = "UPDATE cars SET model = ?, manufacturer_id = ? WHERE id = ?"
                + " AND is_deleted = FALSE";
```

2022-12-09 16:39 UTC, kozhukhovsky approved these changes

2025-11-20 20:28 UTC, closed without merging