Jv join solution
mate-academy/jv-join pull request #593
Opened 2023-04-13 11:54 UTC by dreeeamcatcher

2023-04-13 12:04 UTC, Rommelua requested changes

2023-04-13 12:04 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/CarDaoImpl.java
> +                + "WHERE cd.driver_id = ? AND c.is_deleted = FALSE";
Try to get **Cars** using this SELECT - not only IDs

2023-04-13 12:04 UTC, Rommelua commented on src/main/java/mate/jdbc/service/CarServiceImpl.java
> +        }
do not use System.out.println
```suggestion
        } 
```

2023-04-13 12:04 UTC, Rommelua commented on src/main/java/mate/jdbc/service/CarServiceImpl.java
> +        }
```suggestion
            car.getDrivers().remove(driver);
            carDao.update(car);
       ```

2023-04-14 14:11 UTC, andriy-shulepa approved these changes

2024-09-26 14:52 UTC, closed without merging